openapi: 3.0.0
info:
  title: Exploring Microservices
  version: 0.2.0
  description: Project to explore microservices architecture - Runtimes For Concurrency and Distribution - UniPd

servers:
  - url: http://192.168.59.100
    description: Local Server

tags:
  - name: Users
    description: Users Microservice. Creation and management of users
 

components:
  responses:
    server_error:
      description: Server Error
      content:
        application/json:
          schema:
            type: object
          examples:
            example-0:
              summary: Example 1
              value:
                status: 500
                message:
                  error: Custom message
    validation_error:
      description: Validation Error
      content:
        application/json:
          schema:
            type: object
          examples:
            example-0:
              summary: Example 0
              value:
                status: 422
                message:
                  error: "Invalid fields"
                validation_errors:
                  error_field_1: error message 1
                  error_field_2: error message 2
            example-1:
              summary: Example 1
              value:
                status: 422
                message:
                  error: "Invalid fields"
                validation_errors:
                  name: The name field is required.


    unauthorized_error:
      description: Unauthorized Error
      content:
        application/json:
          schema:
            type: object
          examples:
            example-0:
              summary: Example 0
              value:
                status: 403
                message:
                  error: "Unauthorized"
    warning:
      description: Warning response
      content:
        application/json:
          schema:
            type: object
          examples:
            example-0:
              summary: Example 0
              value:
                status: 199
                message:
                  warning: "Warning message"

paths:
  /users:
    get:
      tags:
        - Users
      summary: Get all users
      description: Get all users
      parameters:
        - in: query
          name: email
          schema:
            type: string
          required: false
          description: Filter by user email
          example: user@example.com


      responses:
        "500":
          $ref: '#/components/responses/server_error'
    post:
      tags:
        - Users
      summary: Store a new user
      description: Store a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: John
                surname:
                  type: string
                  example: Doe
                email:
                  type: string
                  example: user@example.com
                password:
                  type: string
                  example: 12345678
      responses:
        "500":
          $ref: '#/components/responses/server_error'
  /users/{id}:
    get:
      tags:
        - Users
      summary: Get a single user by id
      description: Get a single user by id
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: Numeric ID of the user to get

      responses:
        "500":
          $ref: '#/components/responses/server_error'
    put:
      tags:
        - Users
      summary: Update a user (NYI)
      description: Update a user
      deprecated: true
      responses:
        "500":
          $ref: '#/components/responses/server_error'
    delete:
      tags:
        - Users
      summary: Delete a user (NYI)
      description: Delete a user
      deprecated: true
      responses:
        "500":
          $ref: '#/components/responses/server_error'
  /healthcheck:
    get:
      tags:
        - Users
      summary: Healthcheck
      description: Check the health of the service

      responses:
        "500":
          $ref: '#/components/responses/server_error'

 